// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuYkvv4b2IBypKPaiK9dy1FAU_SrUnjEg',
    appId: '1:319301727482:android:bfb7221e641927096c8543',
    messagingSenderId: '319301727482',
    projectId: 'shop-app-2868c',
    databaseURL: 'https://shop-app-2868c-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-2868c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj12DCi6xU2mMQfYMKKroayh1hsdwuAlU',
    appId: '1:319301727482:ios:b5bd73655a7148216c8543',
    messagingSenderId: '319301727482',
    projectId: 'shop-app-2868c',
    databaseURL: 'https://shop-app-2868c-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-2868c.appspot.com',
    iosClientId: '319301727482-lvh4sedqhrvr0rn6ueqkdpesmubgjkoq.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
